# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kwebrtc_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kwebrtc_demo
  pod 'GoogleWebRTC'

  target 'kwebrtc_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kwebrtc_demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
